### ISSUE TITLE
Error with the syntax

### ISSUE THREAD

**Issue by Anonikat** [gitnew2018/nodejs_peri_downloader#2]
node periscopeDownloader.js "https://prod-video-eu-west-1.periscope.tv/blablablablabla-blablablablabla/live/blablabla/dynamic_playlist.m3u8" "2018-08-21_15.36_1258_😋"
C:\Users\download\Downloads\Descargas PERISCOPE\periscopeDownloader.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by gitnew2018** [comment]
@Anonikat thanks for the report.
Does it happen often? 
I cannot reproduce it, 
Your log says the error happened on line 7.
Line 7 is:     });
I don't know what to do with it, sorry.
